### ISSUE TITLE
Sodaguide Features Todo（2023-2024长期）

### ISSUE THREAD

**Issue by kaluojushi** [kaluojushi/sodaguide#2]
此处是苏打盖待更新的特性，将在计划时间内完成更新。

**开始版块**

- [ ] 版权、商标权纠纷科普【SSS】
- [ ] 吴青峰所有创作【S】

**成员版块**

- [ ] 成员资料【SS】
- [ ] 成员昵称收集【SS】
- [ ] 合作伙伴、峰峰战队补充【S】

**作品版块**

- [ ] 资料收集【S】

**演唱会版块**

- [ ] 资料收集【S】
- [ ] 歌单收集【S】
- [ ] 答题收集【SS】

**百科版块**

- [ ] 词条模式探索【A】

**资源版块**

- [ ] 鱼丁糸歌曲资源【SS】
- [ ] 吴青峰歌曲资源【SS】
- [ ] 鱼丁秘密【A】
- [ ] <https://www.zhihu.com/question/28110668/answer/2926229208> 收录【SSS】

**其他**

- [ ] b 站 琳婧JING 资料整理 <https://www.bilibili.com/read/readlist/rl142216>【SS】
- [ ] b 站视频补链【SSS】
- [ ] 苏打绿地图打卡模式探索【A】

持续更新……

**Comment by kaluojushi** [comment]
【吴青峰新人站团票题目整理0109】
1、青峰首次在政大舞台唱：逃亡；我要的幸福；逆光；Leave Me Alone
2、青峰没有在现场演奏过：电吉他；电贝司；特雷门琴；木笛
3、哪个城市与四季专无关：台东；柏林；北京；东京
4、秋专藏头诗下半句是：（你只见眼前秋）
5、哪首歌由青峰作词作曲：当我们一起走过；频率；十年一刻；控制狂
6、获金曲奖最佳作曲的是：无与伦比的美丽；小情歌；恋人絮语；下雨的夜晚
7、青峰在池塘怪谈演的是：老师；作家；医生；学生
8、推着上山巨石，亲爱？：（薛西佛斯）
9、小宇宙复刻有以下哪首：黑猫白猫；心情电梯；蜘蛛天空；罗生门
10、苏打绿复刻版正名日期：12.10；12.12；12.20；12.22

**Comment by kaluojushi** [comment]
【绿人村团票题目整理0109-1255】
1、《十年一刻》里面的戏曲片段属于哪种类型？越剧；川剧；京剧；粤剧
2、补全《各站停靠》歌词：春立下分际的标杆时，我作了一个梦。我梦见我竟然变成了____：花；蝴蝶；庄周；人
3、《小情歌》出自哪张专辑：陪我歌唱；无与伦比的美丽；小宇宙；苏打绿同名
4、在《未了》这首歌里，有一句歌词同时提到了四位主神：“他午睡、他狂欢、她教大地拾穗；而你靠你蹒跚，支撑自己轮回。”请问午睡的主神是谁？酒神狄俄尼索斯；推石者薛西佛斯；大地之神德墨忒尔；牧神潘
5、《你在烦恼什么》（2011）专辑封面没有哪位团员？何景扬；谢馨仪；史俊威；刘家凯；龚钰祺；吴青峰

**Comment by kaluojushi** [comment]
【绿人村团票题目整理0109-1815】
1、以下哪首歌和影视剧无关？剑雨浮生；幸福额度；我好想你；四季狂想
2、《故事》的MV中，开头和结尾出现的文物是什么？望远镜；留声机；自鸣钟；天球仪
3、收录于《夏／狂热》专辑中，且是其中唯一一首台语歌是什么？彼得与狼；无眠；追追追；煽动
4、《冬　未了》的“未了”二字隐藏在秋专辑里的哪首歌里？你心里最后一个；拾穗；故事；我好想你
5、收录于《苏打绿同名专辑》的歌曲是相对论几？IV；IX；V；VI

**Comment by ZhongLingyuxiu1028** [comment]
请问下有没有相关的内容来源？直接引用维基百科或者是PTT之类的资料吗？对于需要施工的版面有没有大致的思路或者是需要什么样的内容？

**Comment by kaluojushi** [comment]
> 请问下有没有相关的内容来源？直接引用维基百科或者是PTT之类的资料吗？对于需要施工的版面有没有大致的思路或者是需要什么样的内容？

这个list是一个我个人拟的简单的todo事项，表示网站可以更新的部分，很多资料也没有收集，有更多的想法可以一起提出来，或者参与页面编辑，可以看看pr里有其他老师参与的内容

**Comment by CloudYouzzz** [comment]
老师您好，我是之前在b站提出打卡地图的那个，目前我已经把地图做成google map的形式了，链接【https://www.google.com/maps/d/u/0/edit?hl=en&mid=1iJbI1PR1ehtiocxvyshq1qTjWss2voI&ll=21.94247760898999%2C50.449976169135084&z=3】，希望对之后的打卡地图建设有帮助~

**Comment by kaluojushi** [comment]
【2025 Todo】

- [ ] fix: Algolia 搜索重复问题
- [ ] feat: 海外演唱会页面更新
